export * from "./multiply/index";
export * from "./divide/index";
export * from "./percent/index";
export * from "./basics.model";
export * from "./basics.service";
export * from "./basics.component";
export * from "./basics.generate.component";
export * from "./basics.questions.component";
export * from "./basics.results.component";
