openapi: 3.0.0

info:
  title: "MultiTest API"
  version: "1.0.0"
  contact:
    name: Malcolm Pereira
    email: malcolm.j.pereira@gmail.com
tags:
  - name: Basics
    description: Basics Tests
paths:
  /basics:
    get:
      operationId: getBasics
      summary: Get Basic Tests
      tags: [ 'Basics' ]
      responses:
        '200':
          description: OK
components:
            